spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
  instance:
    hostname: peer3